function xfxf()

DF={ 
 xiu , 
 gou ,
 qygdz , 
 dzsjdz , 
 erjdz , 
 goupa , 
 huaxing , 
 jingtou , 
 xianzuguang ,
 csaddr , 
 dtaddr , 
 mrrw ,  
 ydgypy ,  
 xjdiaoxiang ,  
 xhdz , 
 Lonsd , 
 Longj ,  
 xigb ,  
 luzhikg ,  
 yjqfpy ,  
 daol ,  
 kczblpy ,
 kczblpy2 ,
 kczblpy3 ,
 kczblpy4 ,
 kczblpy5 ,
 kczblpy6 ,
 kczblpy7 ,
 zdjl ,
 xhdh ,
 ZYchun ,
 dxbaddr ,
 km_dz ,
 cnaddr ,
 yqaddr ,
 mfdz ,
 Address_clos ,
 ygdz ,
 zspy ,
 hyxx ,
 rsdz ,
 dengjiaddr ,
 lazushuliang ,
 zhayi ,
 zhaf ,
 Character_color ,
 BBMO ,
 sxdz ,
 yanhuadz ,
 ydxzaddr,
 XZDZ, 
 fabao,
}
   AF = { 
      'sddz', 
         'rwdz',
         'qygdz', 
         'dzsjdz', 
         'erjdz', 
         'goupa', 
         'huaxing', 
         'jingtou', 
         'xianzuguang',
         'csaddr', 
         'dtaddr', 
         'mrrw',  
         'ydgypy',  
         'xjdiaoxiang',  
         'xhdz', 
         'Lonsd', 
         'Longj',  
         'xigb',  
         'luzhikg',  
         'yjqfpy',  
         'daol',  
         'kczblpy',
   'kczblpy2',
   'kczblpy3',
   'kczblpy4',
         'kczblpy5',
         'kczblpy6',
         'kczblpy7',
         'zdjl',
         'xhdh',
         'ZYchun',
         'dxbaddr',
         'km_dz',
         'cnaddr',
         'yqaddr',
         'mfdz',
         'Address_clos',
         'ygdz',
         'zspy',
         'hyxx',
   'rsdz',
         'dengjiaddr',
         'lazushuliang',
         'zhayi',
         'zhaf',
         'Character_color',
         'BBMO',
         'sxdz',
         'yanhuadz',
         'ydxzaddr',
         'XZDZ',
         'fabao'
}       
for i=1,#DF do gouSZ=string.format("%08X",DF[i]) print("        "..AF[i].." = ",gouSZ) end

end

xfxf()
function lpp()
print(xztab)
end
lpp()