function xfxf()

DF={ 
 xiu , 
 gou ,
 qygdz , 
 dzsjdz , 
 erjdz , 
 goupa , 
 huaxing , 
 jingtou , 
 xianzuguang ,
 csaddr , 
 dtaddr , 
 mrrw ,  
 ydgypy ,  
 xjdiaoxiang ,  
 xhdz , 
 Lonsd , 
 Longj ,  
 xigb ,  
 luzhikg ,  
 yjqfpy ,  
 daol ,  
 kczblpy ,
 kczblpy2 ,
 kczblpy3 ,
 kczblpy4 ,
 kczblpy5 ,
 kczblpy6 ,
 kczblpy7 ,
 zdjl ,
 xhdh ,
 
 dxbaddr ,

 cnaddr ,
 yqaddr ,
 ZYchun,
 mfdz ,
 Address_clos ,
 ygdz ,
 zspy ,
 hyxx ,
 rsdz ,
 dengjiaddr ,
 lazushuliang ,
 zhayi ,
 zhaf ,
 Character_color ,
 BBMO ,
 sxdz ,
 yanhuadz ,
 hysl,
 hyid,
 name,
 XZDZ, 
 ydgyj,
 ydxj,
 ydslz,
 BZDZ,
 shouhuo,
 sllx
}
   AF = { 
      'sddz', 
         'rwdz',
         'qygdz', 
         'dzsjdz', 
         'erjdz', 
         'goupa', 
         'huaxing', 
         'jingtou', 
         'xianzuguang',
         'csaddr', 
         'dtaddr', 
         'mrrw',  
         'ydgypy',  
         'xjdiaoxiang',  
         'xhdz', 
         'Lonsd', 
         'Longj',  
         'xigb',  
         'luzhikg',  
         'yjqfpy',  
         'daol',  
         'kczblpy',
   'kczblpy2',
   'kczblpy3',
   'kczblpy4',
         'kczblpy5',
         'kczblpy6',
         'kczblpy7',
         'zdjl',
         'xhdh',
        
         'dxbaddr',

         'cnaddr',
         'yqaddr',
         'ZYchun',
         'mfdz',
         'Address_clos',
         'ygdz',
         'zspy',
         'hyxx',
   'rsdz',
         'dengjiaddr',
         'lazushuliang',
         'zhayi',
         'zhaf',
         'Character_color',
         'BBMO',
         'sxdz',
         'yanhuadz',
         'ydxzaddr',
         'hysl',
          'hyid',
          'name',
          'XZDZ', 
          'ydgyj',
          'ydxj',
          'ydslz',
          'BZDZ',
          'shouhuo',
          'sllx'
}       
for i=1,#DF do gouSZ=string.format("%08X",DF[i]) print("        "..AF[i].." = ",gouSZ) end

end

xfxf()
function lpp()
print(xztab)
end
lpp()